Insert into aereopuertos(nombre,pais,codigo) values('Tirana Airport','Albania', 'TIA');
Insert into aereopuertos(nombre,pais,codigo) values('Algovia Airport Memmingen','Alemania', 'FMM');
Insert into aereopuertos(nombre,pais,codigo) values('Berlín Brandeburgo Airport','Alemania', 'BER');
Insert into aereopuertos(nombre,pais,codigo) values('Bremen Airport','Alemania', 'BRE');
Insert into aereopuertos(nombre,pais,codigo) values('Colonia Bonn Airport','Alemania', 'CGN');
Insert into aereopuertos(nombre,pais,codigo) values('Dortmund Airport','Alemania', 'DTM');
Insert into aereopuertos(nombre,pais,codigo) values('Dresde Airport','Alemania', 'DRS');
Insert into aereopuertos(nombre,pais,codigo) values('Dusseldorf Airport','Alemania', 'DUS');
Insert into aereopuertos(nombre,pais,codigo) values('Frankfurt Airport','Alemania', 'FRA');
Insert into aereopuertos(nombre,pais,codigo) values('Frankfurt-Hahn Airport','Alemania', 'HHN');
Insert into aereopuertos(nombre,pais,codigo) values('Friedrichshafen Airport','Alemania', 'FDH');
Insert into aereopuertos(nombre,pais,codigo) values('Hamburgo Airport','Alemania', 'HAM');
Insert into aereopuertos(nombre,pais,codigo) values('Hanóver Airport','Alemania', 'HAJ');
Insert into aereopuertos(nombre,pais,codigo) values('Karlsruhe Baden-Baden Airport','Alemania', 'FKB');
Insert into aereopuertos(nombre,pais,codigo) values('Leipzig Halle Airport','Alemania', 'LEJ');
Insert into aereopuertos(nombre,pais,codigo) values('Múnich Airport','Alemania', 'MUC');
Insert into aereopuertos(nombre,pais,codigo) values('Münster Osnabrück Airport','Alemania', 'FMO');
Insert into aereopuertos(nombre,pais,codigo) values('Núremberg Airport','Alemania', 'NUE');
Insert into aereopuertos(nombre,pais,codigo) values('Paderborn Lippstadt Airport','Alemania', 'PAD');
Insert into aereopuertos(nombre,pais,codigo) values('Stuttgart Airport','Alemania', 'STR');
Insert into aereopuertos(nombre,pais,codigo) values('Weeze Airport','Alemania', 'NRN');
Insert into aereopuertos(nombre,pais,codigo) values('Ereván Zvartnots Airport','Armenia', 'EVN');
Insert into aereopuertos(nombre,pais,codigo) values('Graz Airport','Austria', 'GRZ');
Insert into aereopuertos(nombre,pais,codigo) values('Innsbruck Airport','Austria', 'INN');
Insert into aereopuertos(nombre,pais,codigo) values('Klagenfurt Airport','Austria', 'KLU');
Insert into aereopuertos(nombre,pais,codigo) values('Linz Airport','Austria', 'LNZ');
Insert into aereopuertos(nombre,pais,codigo) values('Salzburgo Airport','Austria', 'SZG');
Insert into aereopuertos(nombre,pais,codigo) values('Viena Airport','Austria', 'VIE');
Insert into aereopuertos(nombre,pais,codigo) values('Bakú Airport','Azerbaiyán', 'GYD');
Insert into aereopuertos(nombre,pais,codigo) values('Amberes Airport','Bélgica', 'ANR');
Insert into aereopuertos(nombre,pais,codigo) values('Bruselas Airport','Bélgica', 'BRU');
Insert into aereopuertos(nombre,pais,codigo) values('Charleroi Airport','Bélgica', 'CRL');
Insert into aereopuertos(nombre,pais,codigo) values('Lieja Airport','Bélgica', 'LGG');
Insert into aereopuertos(nombre,pais,codigo) values('Ostende Brujas Airport','Bélgica', 'OST');
Insert into aereopuertos(nombre,pais,codigo) values('Minsk Airport','Bielorrusia', 'MSQ');
Insert into aereopuertos(nombre,pais,codigo) values('Sarajevo Airport','Bosnia y Herzegovina', 'SJJ');
Insert into aereopuertos(nombre,pais,codigo) values('Tuzla Airport','Bosnia y Herzegovina', 'TZL');
Insert into aereopuertos(nombre,pais,codigo) values('Burgas Airport','Bulgaria', 'BOJ');
Insert into aereopuertos(nombre,pais,codigo) values('Sofía Airport','Bulgaria', 'SOF');
Insert into aereopuertos(nombre,pais,codigo) values('Varna Airport','Bulgaria', 'VAR');
Insert into aereopuertos(nombre,pais,codigo) values('Lárnaca Airport','Chipre', 'LCA');
Insert into aereopuertos(nombre,pais,codigo) values('Pafos Airport','Chipre', 'PFO');
Insert into aereopuertos(nombre,pais,codigo) values('Dubrovnik Airport','Croacia', 'DBV');
Insert into aereopuertos(nombre,pais,codigo) values('Pula Airport','Croacia', 'PUY');
Insert into aereopuertos(nombre,pais,codigo) values('Split Airport','Croacia', 'SPU');
Insert into aereopuertos(nombre,pais,codigo) values('Zadar Airport','Croacia', 'ZAD');
Insert into aereopuertos(nombre,pais,codigo) values('Zagreb Airport','Croacia', 'ZAG');
Insert into aereopuertos(nombre,pais,codigo) values('Aalborg Airport','Dinamarca', 'AAL');
Insert into aereopuertos(nombre,pais,codigo) values('Aarhus Airport','Dinamarca', 'AAR');
Insert into aereopuertos(nombre,pais,codigo) values('Billund Airport','Dinamarca', 'BLL');
Insert into aereopuertos(nombre,pais,codigo) values('Copenhague Airport','Dinamarca', 'CPH');
Insert into aereopuertos(nombre,pais,codigo) values('Vágar Airport','Dinamarca', 'FAE');
Insert into aereopuertos(nombre,pais,codigo) values('Bratislava Airport','Eslovaquia', 'BTS');
Insert into aereopuertos(nombre,pais,codigo) values('Košice Airport','Eslovaquia', 'KSC');
Insert into aereopuertos(nombre,pais,codigo) values('Liubliana Airport','Eslovenia', 'LJU');
Insert into aereopuertos(nombre,pais,codigo) values('Alicante Airport','España', 'ALC');
Insert into aereopuertos(nombre,pais,codigo) values('Almería Airport','España', 'LEI');
Insert into aereopuertos(nombre,pais,codigo) values('Asturias Airport','España', 'OVD');
Insert into aereopuertos(nombre,pais,codigo) values('Barcelona Airport','España', 'BCN');
Insert into aereopuertos(nombre,pais,codigo) values('Bilbao Airport','España', 'BIO');
Insert into aereopuertos(nombre,pais,codigo) values('Fuerteventura Airport','España', 'FUE');
Insert into aereopuertos(nombre,pais,codigo) values('Girona Airport','España', 'GRO');
Insert into aereopuertos(nombre,pais,codigo) values('Gran Canaria Airport','España', 'LPA');
Insert into aereopuertos(nombre,pais,codigo) values('Granada-Jaén Airport','España', 'GRX');
Insert into aereopuertos(nombre,pais,codigo) values('Ibiza Airport','España', 'IBZ');
Insert into aereopuertos(nombre,pais,codigo) values('Jerez Airport','España', 'XRY');
Insert into aereopuertos(nombre,pais,codigo) values('La Palma Airport','España', 'SPC');
Insert into aereopuertos(nombre,pais,codigo) values('Lanzarote Airport','España', 'ACE');
Insert into aereopuertos(nombre,pais,codigo) values('Madrid Barajas Airport','España', 'MAD');
Insert into aereopuertos(nombre,pais,codigo) values('Málaga Airport','España', 'AGP');
Insert into aereopuertos(nombre,pais,codigo) values('Menorca Airport','España', 'MAH');
Insert into aereopuertos(nombre,pais,codigo) values('Palma de Mallorca Airport','España', 'PMI');
Insert into aereopuertos(nombre,pais,codigo) values('Región de Murcia Airport','España', 'RMU');
Insert into aereopuertos(nombre,pais,codigo) values('Reus Airport','España', 'REU');
Insert into aereopuertos(nombre,pais,codigo) values('Santander Airport','España', 'SDR');
Insert into aereopuertos(nombre,pais,codigo) values('Santiago de Compostela Airport','España', 'SCQ');
Insert into aereopuertos(nombre,pais,codigo) values('Sevilla Airport','España', 'SVQ');
Insert into aereopuertos(nombre,pais,codigo) values('Tenerife Norte Airport','España', 'TFN');
Insert into aereopuertos(nombre,pais,codigo) values('Tenerife Sur Airport','España', 'TFS');
Insert into aereopuertos(nombre,pais,codigo) values('Valencia Airport','España', 'VLC');
Insert into aereopuertos(nombre,pais,codigo) values('Zaragoza Airport','España', 'ZAZ');
Insert into aereopuertos(nombre,pais,codigo) values('Tallin Airport','Estonia', 'TLL');
Insert into aereopuertos(nombre,pais,codigo) values('Helsinki Airport','Finlandia', 'HEL');
Insert into aereopuertos(nombre,pais,codigo) values('Oulu Airport','Finlandia', 'OUL');
Insert into aereopuertos(nombre,pais,codigo) values('Rovaniemi Airport','Finlandia', 'RVN');
Insert into aereopuertos(nombre,pais,codigo) values('Tampere Airport','Finlandia', 'TMP');
Insert into aereopuertos(nombre,pais,codigo) values('Turku Airport','Finlandia', 'TKU');
Insert into aereopuertos(nombre,pais,codigo) values('Vaasa Airport','Finlandia', 'VAA');
Insert into aereopuertos(nombre,pais,codigo) values('Ajaccio Airport','Francia', 'AJA');
Insert into aereopuertos(nombre,pais,codigo) values('Bastia Airport','Francia', 'BIA');
Insert into aereopuertos(nombre,pais,codigo) values('Bergerac Airport','Francia', 'EGC');
Insert into aereopuertos(nombre,pais,codigo) values('Biarritz Airport','Francia', 'BIQ');
Insert into aereopuertos(nombre,pais,codigo) values('Brest Bretaña Airport','Francia', 'BES');
Insert into aereopuertos(nombre,pais,codigo) values('Burdeos Airport','Francia', 'BOD');
Insert into aereopuertos(nombre,pais,codigo) values('Estrasburgo Airport','Francia', 'SXB');
Insert into aereopuertos(nombre,pais,codigo) values('Figari Sud Corse Airport','Francia', 'FSC');
Insert into aereopuertos(nombre,pais,codigo) values('Lille Airport','Francia', 'LIL');
Insert into aereopuertos(nombre,pais,codigo) values('Lyon-Saint Exupéry Airport','Francia', 'LYS');
Insert into aereopuertos(nombre,pais,codigo) values('Marsella Airport','Francia', 'MRS');
Insert into aereopuertos(nombre,pais,codigo) values('Montpellier Airport','Francia', 'MPL');
Insert into aereopuertos(nombre,pais,codigo) values('Nantes Airport','Francia', 'NTE');
Insert into aereopuertos(nombre,pais,codigo) values('Niza Airport','Francia', 'NCE');
Insert into aereopuertos(nombre,pais,codigo) values('París Beauvais Airport','Francia', 'BVA');
Insert into aereopuertos(nombre,pais,codigo) values('París Charles de Gaulle Airport','Francia', 'CDG');
Insert into aereopuertos(nombre,pais,codigo) values('París Orly Airport','Francia', 'ORY');
Insert into aereopuertos(nombre,pais,codigo) values('Rennes Bretaña Airport','Francia', 'RNS');
Insert into aereopuertos(nombre,pais,codigo) values('Réunion Roland Garros Airport','Francia', 'RUN');
Insert into aereopuertos(nombre,pais,codigo) values('Toulon-Hyères Airport','Francia', 'TLN');
Insert into aereopuertos(nombre,pais,codigo) values('Toulouse Blagnac Airport','Francia', 'TLS');
Insert into aereopuertos(nombre,pais,codigo) values('Kutaisi Airport','Georgia', 'KUT');
Insert into aereopuertos(nombre,pais,codigo) values('Tiflis Airport','Georgia', 'TBS');
Insert into aereopuertos(nombre,pais,codigo) values('Atenas Airport','Grecia', 'ATH');
Insert into aereopuertos(nombre,pais,codigo) values('Corfú Airport','Grecia', 'CFU');
Insert into aereopuertos(nombre,pais,codigo) values('Cos Airport','Grecia', 'KGS');
Insert into aereopuertos(nombre,pais,codigo) values('Heraklion Airport','Grecia', 'HER');
Insert into aereopuertos(nombre,pais,codigo) values('La Canea Airport','Grecia', 'CHQ');
Insert into aereopuertos(nombre,pais,codigo) values('Mykonos Airport','Grecia', 'JMK');
Insert into aereopuertos(nombre,pais,codigo) values('Rodas Airport','Grecia', 'RHO');
Insert into aereopuertos(nombre,pais,codigo) values('Santorini Airport','Grecia', 'JTR');
Insert into aereopuertos(nombre,pais,codigo) values('Tesalónica Airport','Grecia', 'SKG');
Insert into aereopuertos(nombre,pais,codigo) values('Zante Airport','Grecia', 'ZTH');
Insert into aereopuertos(nombre,pais,codigo) values('Budapest Airport','Hungría', 'BUD');
Insert into aereopuertos(nombre,pais,codigo) values('Debrecen Airport','Hungría', 'DEB');
Insert into aereopuertos(nombre,pais,codigo) values('Cork Airport','Irlanda', 'ORK');
Insert into aereopuertos(nombre,pais,codigo) values('Dublín Airport','Irlanda', 'DUB');
Insert into aereopuertos(nombre,pais,codigo) values('Irlanda Oeste Airport Knock','Irlanda', 'NOC');
Insert into aereopuertos(nombre,pais,codigo) values('Kerry Airport','Irlanda', 'KIR');
Insert into aereopuertos(nombre,pais,codigo) values('Shannon Airport','Irlanda', 'SNN');
Insert into aereopuertos(nombre,pais,codigo) values('Keflavík Airport','Islandia', 'KEF');
Insert into aereopuertos(nombre,pais,codigo) values('Alguer Airport','Italia', 'AHO');
Insert into aereopuertos(nombre,pais,codigo) values('Ancona Airport','Italia', 'AOI');
Insert into aereopuertos(nombre,pais,codigo) values('Bari Airport','Italia', 'BRI');
Insert into aereopuertos(nombre,pais,codigo) values('Bérgamo Airport','Italia', 'BGY');
Insert into aereopuertos(nombre,pais,codigo) values('Bolonia Airport','Italia', 'BLQ');
Insert into aereopuertos(nombre,pais,codigo) values('Brindisi Airport','Italia', 'BDS');
Insert into aereopuertos(nombre,pais,codigo) values('Cagliari Airport','Italia', 'CAG');
Insert into aereopuertos(nombre,pais,codigo) values('Catania Fontanarossa Airport','Italia', 'CTA');
Insert into aereopuertos(nombre,pais,codigo) values('Comiso Airport','Italia', 'CIY');
Insert into aereopuertos(nombre,pais,codigo) values('Florencia Airport','Italia', 'FLR');
Insert into aereopuertos(nombre,pais,codigo) values('Génova Airport','Italia', 'GOA');
Insert into aereopuertos(nombre,pais,codigo) values('Lamezia Terme Airport','Italia', 'SUF');
Insert into aereopuertos(nombre,pais,codigo) values('Milán Linate Airport','Italia', 'LIN');
Insert into aereopuertos(nombre,pais,codigo) values('Milán Malpensa Airport','Italia', 'MXP');
Insert into aereopuertos(nombre,pais,codigo) values('Nápoles Airport','Italia', 'NAP');
Insert into aereopuertos(nombre,pais,codigo) values('Olbia Costa Smeralda Airport','Italia', 'OLB');
Insert into aereopuertos(nombre,pais,codigo) values('Palermo Airport','Italia', 'PMO');
Insert into aereopuertos(nombre,pais,codigo) values('Perugia Airport','Italia', 'PEG');
Insert into aereopuertos(nombre,pais,codigo) values('Pescara Airport','Italia', 'PSR');
Insert into aereopuertos(nombre,pais,codigo) values('Pisa Airport','Italia', 'PSA');
Insert into aereopuertos(nombre,pais,codigo) values('Roma Ciampino Airport','Italia', 'CIA');
Insert into aereopuertos(nombre,pais,codigo) values('Roma Fiumicino Airport','Italia', 'FCO');
Insert into aereopuertos(nombre,pais,codigo) values('Trapani Airport','Italia', 'TPS');
Insert into aereopuertos(nombre,pais,codigo) values('Treviso Airport','Italia', 'TSF');
Insert into aereopuertos(nombre,pais,codigo) values('Trieste Airport','Italia', 'TRS');
Insert into aereopuertos(nombre,pais,codigo) values('Turín Airport','Italia', 'TRN');
Insert into aereopuertos(nombre,pais,codigo) values('Venecia Airport','Italia', 'VCE');
Insert into aereopuertos(nombre,pais,codigo) values('Verona Airport','Italia', 'VRN');
Insert into aereopuertos(nombre,pais,codigo) values('Almatý Airport','Kazajistán', 'ALA');
Insert into aereopuertos(nombre,pais,codigo) values('Nursultán Nazarbayev Airport','Kazajistán', 'NQZ');
Insert into aereopuertos(nombre,pais,codigo) values('Pristina Airport','Kosovo', 'PRN');
Insert into aereopuertos(nombre,pais,codigo) values('Riga Airport','Letonia', 'RIX');
Insert into aereopuertos(nombre,pais,codigo) values('Kaunas Airport','Lituania', 'KUN');
Insert into aereopuertos(nombre,pais,codigo) values('Vilnius Airport','Lituania', 'VNO');
Insert into aereopuertos(nombre,pais,codigo) values('Luxemburgo Airport','Luxemburgo', 'LUX');
Insert into aereopuertos(nombre,pais,codigo) values('Skopje Airport','Macedonia del Norte', 'SKP');
Insert into aereopuertos(nombre,pais,codigo) values('Malta Airport','Malta', 'MLA');
Insert into aereopuertos(nombre,pais,codigo) values('Chisináu Airport','Moldavia', 'KIV');
Insert into aereopuertos(nombre,pais,codigo) values('Podgorica Airport','Montenegro', 'TGD');
Insert into aereopuertos(nombre,pais,codigo) values('Tivat Airport','Montenegro', 'TIV');
Insert into aereopuertos(nombre,pais,codigo) values('Ålesund Airport','Noruega', 'AES');
Insert into aereopuertos(nombre,pais,codigo) values('Bergen Airport','Noruega', 'BGO');
Insert into aereopuertos(nombre,pais,codigo) values('Bodø Airport','Noruega', 'BOO');
Insert into aereopuertos(nombre,pais,codigo) values('Haugesund Airport','Noruega', 'HAU');
Insert into aereopuertos(nombre,pais,codigo) values('Kristiansand Airport','Noruega', 'KRS');
Insert into aereopuertos(nombre,pais,codigo) values('Oslo Airport','Noruega', 'OSL');
Insert into aereopuertos(nombre,pais,codigo) values('Sandefjord Airport Torp','Noruega', 'TRF');
Insert into aereopuertos(nombre,pais,codigo) values('Stavanger Airport','Noruega', 'SVG');
Insert into aereopuertos(nombre,pais,codigo) values('Tromsø Airport','Noruega', 'TOS');
Insert into aereopuertos(nombre,pais,codigo) values('Trondheim Airport','Noruega', 'TRD');
Insert into aereopuertos(nombre,pais,codigo) values('Ámsterdam Airport Schiphol','Países Bajos', 'AMS');
Insert into aereopuertos(nombre,pais,codigo) values('Eindhoven Airport','Países Bajos', 'EIN');
Insert into aereopuertos(nombre,pais,codigo) values('Groninga Airport Eelde','Países Bajos', 'GRQ');
Insert into aereopuertos(nombre,pais,codigo) values('Maastricht Aachen Airport','Países Bajos', 'MST');
Insert into aereopuertos(nombre,pais,codigo) values('Róterdam La Haya Airport','Países Bajos', 'RTM');
Insert into aereopuertos(nombre,pais,codigo) values('Breslavia Airport','Polonia', 'WRO');
Insert into aereopuertos(nombre,pais,codigo) values('Cracovia Airport','Polonia', 'KRK');
Insert into aereopuertos(nombre,pais,codigo) values('Gdansk Airport','Polonia', 'GDN');
Insert into aereopuertos(nombre,pais,codigo) values('Katowice Airport','Polonia', 'KTW');
Insert into aereopuertos(nombre,pais,codigo) values('Poznan Airport','Polonia', 'POZ');
Insert into aereopuertos(nombre,pais,codigo) values('Szczecin-Goleniów Airport','Polonia', 'SZZ');
Insert into aereopuertos(nombre,pais,codigo) values('Varsovia Airport','Polonia', 'WAW');
Insert into aereopuertos(nombre,pais,codigo) values('Varsovia Modlin Airport','Polonia', 'WMI');
Insert into aereopuertos(nombre,pais,codigo) values('Faro Airport','Portugal', 'FAO');
Insert into aereopuertos(nombre,pais,codigo) values('Lisboa Airport','Portugal', 'LIS');
Insert into aereopuertos(nombre,pais,codigo) values('Madeira Airport','Portugal', 'FNC');
Insert into aereopuertos(nombre,pais,codigo) values('Oporto Airport','Portugal', 'OPO');
Insert into aereopuertos(nombre,pais,codigo) values('Ponta Delgada Airport','Portugal', 'PDL');
Insert into aereopuertos(nombre,pais,codigo) values('Aberdeen Airport','Reino Unido', 'ABZ');
Insert into aereopuertos(nombre,pais,codigo) values('Belfast City Airport','Reino Unido', 'BHD');
Insert into aereopuertos(nombre,pais,codigo) values('Belfast International Airport','Reino Unido', 'BFS');
Insert into aereopuertos(nombre,pais,codigo) values('Birmingham Airport','Reino Unido', 'BHX');
Insert into aereopuertos(nombre,pais,codigo) values('Bristol Airport','Reino Unido', 'BRS');
Insert into aereopuertos(nombre,pais,codigo) values('Cardiff Airport','Reino Unido', 'CWL');
Insert into aereopuertos(nombre,pais,codigo) values('Doncaster Sheffield Airport','Reino Unido', 'DSA');
Insert into aereopuertos(nombre,pais,codigo) values('East Midlands Airport','Reino Unido', 'EMA');
Insert into aereopuertos(nombre,pais,codigo) values('Edimburgo Airport','Reino Unido', 'EDI');
Insert into aereopuertos(nombre,pais,codigo) values('Exeter Airport','Reino Unido', 'EXT');
Insert into aereopuertos(nombre,pais,codigo) values('Glasgow Airport','Reino Unido', 'GLA');
Insert into aereopuertos(nombre,pais,codigo) values('Glasgow Prestwick Airport','Reino Unido', 'PIK');
Insert into aereopuertos(nombre,pais,codigo) values('Humberside Airport','Reino Unido', 'HUY');
Insert into aereopuertos(nombre,pais,codigo) values('Jersey Airport','Reino Unido', 'JER');
Insert into aereopuertos(nombre,pais,codigo) values('Leeds Bradford Airport','Reino Unido', 'LBA');
Insert into aereopuertos(nombre,pais,codigo) values('Liverpool Airport','Reino Unido', 'LPL');
Insert into aereopuertos(nombre,pais,codigo) values('Londres City Airport','Reino Unido', 'LCY');
Insert into aereopuertos(nombre,pais,codigo) values('Londres Gatwick Airport','Reino Unido', 'LGW');
Insert into aereopuertos(nombre,pais,codigo) values('Londres Heathrow Airport','Reino Unido', 'LHR');
Insert into aereopuertos(nombre,pais,codigo) values('Londres Luton Airport','Reino Unido', 'LTN');
Insert into aereopuertos(nombre,pais,codigo) values('Londres Southend Airport','Reino Unido', 'SEN');
Insert into aereopuertos(nombre,pais,codigo) values('Londres Stansted Airport','Reino Unido', 'STN');
Insert into aereopuertos(nombre,pais,codigo) values('Mánchester Airport','Reino Unido', 'MAN');
Insert into aereopuertos(nombre,pais,codigo) values('Newcastle Airport','Reino Unido', 'NCL');
Insert into aereopuertos(nombre,pais,codigo) values('Southampton Airport','Reino Unido', 'SOU');
Insert into aereopuertos(nombre,pais,codigo) values('Brno Airport','República Checa', 'BRQ');
Insert into aereopuertos(nombre,pais,codigo) values('Praga Airport','República Checa', 'PRG');
Insert into aereopuertos(nombre,pais,codigo) values('Bucarest Henri Coanda Airport','Rumania', 'OTP');
Insert into aereopuertos(nombre,pais,codigo) values('Cluj-Napoca Airport','Rumania', 'CLJ');
Insert into aereopuertos(nombre,pais,codigo) values('Iasi Airport','Rumania', 'IAS');
Insert into aereopuertos(nombre,pais,codigo) values('Sibiu Airport','Rumania', 'SBZ');
Insert into aereopuertos(nombre,pais,codigo) values('Timisoara Airport','Rumania', 'TSR');
Insert into aereopuertos(nombre,pais,codigo) values('Ekaterimburgo Koltsovo Airport','Rusia', 'SVX');
Insert into aereopuertos(nombre,pais,codigo) values('Krasnodar Airport','Rusia', 'KRR');
Insert into aereopuertos(nombre,pais,codigo) values('Moscú Domodédovo Airport','Rusia', 'DME');
Insert into aereopuertos(nombre,pais,codigo) values('Moscú Sheremetyevo Airport','Rusia', 'SVO');
Insert into aereopuertos(nombre,pais,codigo) values('Moscú Vnúkovo Airport','Rusia', 'VKO');
Insert into aereopuertos(nombre,pais,codigo) values('Moscú Zhukovski Airport','Rusia', 'ZIA');
Insert into aereopuertos(nombre,pais,codigo) values('Novosibirsk Tolmachevo Airport','Rusia', 'OVB');
Insert into aereopuertos(nombre,pais,codigo) values('San Petersburgo Púlkovo Airport','Rusia', 'LED');
Insert into aereopuertos(nombre,pais,codigo) values('Sochi Airport','Rusia', 'AER');
Insert into aereopuertos(nombre,pais,codigo) values('Belgrado Nikola Tesla Airport','Serbia', 'BEG');
Insert into aereopuertos(nombre,pais,codigo) values('Niš Airport','Serbia', 'INI');
Insert into aereopuertos(nombre,pais,codigo) values('Estocolmo Arlanda Airport','Suecia', 'ARN');
Insert into aereopuertos(nombre,pais,codigo) values('Estocolmo Bromma Airport','Suecia', 'BMA');
Insert into aereopuertos(nombre,pais,codigo) values('Estocolmo Skavsta Airport','Suecia', 'NYO');
Insert into aereopuertos(nombre,pais,codigo) values('Estocolmo Västerås Airport','Suecia', 'VST');
Insert into aereopuertos(nombre,pais,codigo) values('Gotemburgo Landvetter Airport','Suecia', 'GOT');
Insert into aereopuertos(nombre,pais,codigo) values('Malmö Airport','Suecia', 'MMX');
Insert into aereopuertos(nombre,pais,codigo) values('Basilea Mulhouse Friburgo Airport','Suiza', 'BSL');
Insert into aereopuertos(nombre,pais,codigo) values('Ginebra Airport','Suiza', 'GVA');
Insert into aereopuertos(nombre,pais,codigo) values('Zúrich Airport','Suiza', 'ZRH');
Insert into aereopuertos(nombre,pais,codigo) values('Adana Airport','Turquía', 'ADA');
Insert into aereopuertos(nombre,pais,codigo) values('Ankara Esenboga Airport','Turquía', 'ESB');
Insert into aereopuertos(nombre,pais,codigo) values('Antalya Airport','Turquía', 'AYT');
Insert into aereopuertos(nombre,pais,codigo) values('Dalaman Airport','Turquía', 'DLM');
Insert into aereopuertos(nombre,pais,codigo) values('Esmirna Adnan Menderes Airport','Turquía', 'ADB');
Insert into aereopuertos(nombre,pais,codigo) values('Estambul Airport','Turquía', 'IST');
Insert into aereopuertos(nombre,pais,codigo) values('Estambul Sabiha Gökcen Airport','Turquía', 'SAW');
Insert into aereopuertos(nombre,pais,codigo) values('Milas-Bodrum Airport','Turquía', 'BJV');
Insert into aereopuertos(nombre,pais,codigo) values('Trebisonda Airport','Turquía', 'TZX');
Insert into aereopuertos(nombre,pais,codigo) values('Járkov Airport','Ucrania', 'HRK');
Insert into aereopuertos(nombre,pais,codigo) values('Kiev Boryspil Airport','Ucrania', 'KBP');
Insert into aereopuertos(nombre,pais,codigo) values('Kiev Zhuliany Airport','Ucrania', 'IEV');
Insert into aereopuertos(nombre,pais,codigo) values('Lviv Airport','Ucrania', 'LWO');
Insert into aereopuertos(nombre,pais,codigo) values('Odesa Airport','Ucrania', 'ODS');
